# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-27 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignLeads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Assign Leads',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=250)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='Active/Inactive')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=250)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='Active/Inactive')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeadStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='Active/Inactive')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'My Lead Status',
            },
        ),
        migrations.CreateModel(
            name='LeadStatusType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_type', models.CharField(max_length=250)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='Active/Inactive')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Status Type',
            },
        ),
        migrations.CreateModel(
            name='OrganizationDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('organisation_name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('fax', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=250, null=True)),
                ('address', models.TextField(null=True)),
                ('website', models.CharField(max_length=500, null=True)),
                ('description', models.TextField(null=True)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='Active/Inactive')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Organization Details',
            },
        ),
        migrations.CreateModel(
            name='OrganizationLeadDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person', models.CharField(max_length=250, null=True)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=250, null=True)),
                ('lead_title', models.CharField(blank=True, max_length=250, null=True)),
                ('convert', models.IntegerField(default=0)),
                ('discount', models.FloatField()),
                ('description', models.TextField(null=True)),
                ('meeting_date', models.DateField(null=True)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='Active/Inactive')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch.Branch')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.Department')),
                ('lead_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.LeadSource')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.OrganizationDetails')),
            ],
            options={
                'verbose_name_plural': 'Lead Details',
            },
        ),
    ]
