# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-29 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20180827_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationleaddetails',
            name='lead_closed_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='organizationleaddetails',
            name='selling_price',
            field=models.FloatField(null=True),
        ),
    ]
