# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-04 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_auto_20180904_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationleaddetails',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organizationleaddetails',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organizationleaddetails',
            name='lead_closed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organizationleaddetails',
            name='meeting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organizationleaddetails',
            name='selling_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
