# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-29 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_auto_20180829_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadstatustype',
            name='isEditable',
            field=models.BooleanField(default=1),
        ),
    ]
