# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-29 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_auto_20180829_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='reasontype',
            name='reason',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
