# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-06 03:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_auto_20180905_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationleaddetails',
            name='lead_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.LeadSource'),
        ),
        migrations.AlterField(
            model_name='organizationleaddetails',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
    ]
