# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-17 06:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_auto_20180906_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignleads',
            name='assignTo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='employee.Employee'),
        ),
    ]
