# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-15 12:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_organizationleaddetails_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadstatus',
            name='status',
        ),
    ]
