# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-04 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.IntegerField(default=1),
        ),
    ]
