# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-04 12:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20180904_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeebranch',
            name='user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
