# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-04 12:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20180904_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeebranch',
            name='employee',
        ),
    ]
