# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-29 07:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20180829_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mediaType', models.CharField(choices=[('video', 'Video'), ('image', 'Image'), ('ppt', 'PPT'), ('doc', 'DOC')], max_length=50)),
                ('mediaUrl', models.TextField()),
                ('activityType', models.CharField(choices=[('testimonial', 'Testimonial'), ('equipment', 'Equipment'), ('competitor', 'Competitor')], max_length=200)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
            ],
        ),
    ]
