# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-04 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_remove_employeebranch_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeebranch',
            name='employee',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.Employee'),
        ),
    ]
