# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-05 08:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_auto_20181005_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='created_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
