# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-04 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='company_email',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
