# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-04 12:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20181004_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='user',
        ),
    ]
