# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-05 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_auto_20181005_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='companiesusers',
            name='is_admin',
            field=models.IntegerField(default=0),
        ),
    ]
