# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-05 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_auto_20181005_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companiesusers',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='companiesusers',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
