# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-08 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0003_auto_20181008_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.CompaniesUsers'),
        ),
    ]
