# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-12 11:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Repo',
            new_name='Report',
        ),
    ]
