# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-12 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0002_auto_20180912_1640'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Report',
            new_name='Reportt',
        ),
    ]
