# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-12 11:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0003_auto_20180912_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportt',
            old_name='product_name',
            new_name='product_namee',
        ),
    ]
