# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-12 11:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0004_auto_20180912_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportt',
            name='product_namee',
        ),
    ]
