# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-12 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0005_remove_reportt_product_namee'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentWiseReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ProductWiseReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
            ],
        ),
    ]
