# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-12 11:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0006_departmentwisereport_productwisereport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentwisereport',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='productwisereport',
            name='product_name',
        ),
    ]
