# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-12 11:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0007_auto_20180912_1652'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reportt',
        ),
    ]
