# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-12 11:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0008_delete_reportt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DepartmentWiseReport',
        ),
        migrations.DeleteModel(
            name='ProductWiseReport',
        ),
    ]
