# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-27 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0001_initial'),
        ('achievement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigngoal',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch.Branch'),
        ),
        migrations.AddField(
            model_name='assigngoal',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievement.Goal'),
        ),
    ]
