# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-29 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0002_auto_20180827_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='target',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='goalmatrix',
            name='target',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='goalmatrix',
            name='goal_type',
            field=models.CharField(choices=[('amount', 'Amount'), ('unit', 'Unit')], help_text='Type', max_length=20),
        ),
    ]
