# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-03 05:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0003_auto_20180829_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assigngoal',
            name='goal_type',
        ),
    ]
