# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-03 08:58
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0004_remove_assigngoal_goal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigngoal',
            name='assignTo',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='branch', chained_model_field='branch', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fetch_assign', to='employee.EmployeeBranch'),
        ),
    ]
